require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sequel

AllCops:
  NewCops: enable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 40

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
