version: "3.8"

services:
  web:
    image: mradmacher/paleolog:latest
    ports:
      - "80:9292"
    volumes:
      - sqlite:/home/paleolog/db
      - uploads:/home/paleolog/web/public/images

volumes:
  sqlite:
  uploads:
