version: "3.8"

services:
  web:
    build:
      context: .
      target: development
      args:
        USER_UID: "${USER_UID:-1001}"
    command: bundle exec rackup -o 0.0.0.0
    ports:
      - 9292:9292
    volumes:
      - ./:/home/paleolog
