version: "3.8"

services:
  web:
    image: mradmacher/paleolog:latest
    ports:
      - "80:9292"
    environment:
      PALEOLOG_DB_URI: "sqlite://data/development.db"
    volumes:
      - ./data/db:/home/paleolog/data
      - ./data/uploads:/home/paleolog/web/public/images
