version: "3.8"

services:
  testdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: paleolog
      POSTGRES_USER: paleolog
      POSTGRES_DB: paleolog
    ports:
      - 5433:5432
    volumes:
      - ./db/test_postgres:/var/lib/postgresql/data
