version: "3.8"

services:
  db:
    image: postgres:14.8
    environment:
      POSTGRES_PASSWORD: paleolog
      POSTGRES_USER: paleolog
      POSTGRES_DB: paleolog
    ports:
      - 5434:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
  testdb:
    image: postgres:14.8
    environment:
      POSTGRES_PASSWORD: paleolog
      POSTGRES_USER: paleolog
      POSTGRES_DB: paleolog
    ports:
      - 5433:5432
    volumes:
      - ./db/test_postgres:/var/lib/postgresql/data
  #web:
  #  build:
  #    context: .
  #    target: development
  #    args:
  #      USER_UID: "${USER_UID:-1001}"
  #  command: bundle exec rackup -o 0.0.0.0
  #  environment:
  #    PALEOLOG_DB_URI: "postgres://paleolog:paleolog@db/paleolog"
  #    PALEOLOG_DB_MAX_CONNECTIONS: 4
  #  ports:
  #    - 9292:9292
  #  volumes:
  #    - ./:/home/paleolog
