version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PALEOLOG_DB_PASSWORD}
      POSTGRES_USER: paleolog
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    image: mradmacher/paleolog:latest
    ports:
      - "80:9292"
    environment:
      PALEOLOG_DB_URI: "postgres://paleolog:${PALEOLOG_DB_PASSWORD}@db/paleolog"
    volumes:
      - sqlite:/home/paleolog/db
      - uploads:/home/paleolog/web/public/images

volumes:
  postgres:
  sqlite:
  uploads:
