# frozen_string_literal: true

require 'paleolog/repo/config'
require 'paleolog/repo/choice'
require 'paleolog/repo/counting'
require 'paleolog/repo/group'
require 'paleolog/repo/feature'
require 'paleolog/repo/field'
require 'paleolog/repo/image'
require 'paleolog/repo/occurrence'
require 'paleolog/repo/project'
require 'paleolog/repo/sample'
require 'paleolog/repo/section'
require 'paleolog/repo/species'
require 'paleolog/repo/user'
